apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ppl-app

resources:
  - ../../base

images:
  - name: PLACEHOLDER_IMAGE
    newName: docker.io/stevensetiawankuliah/ppl-c-steven-app
    newTag: sha-837c44d

patches:
  - target:
      kind: Deployment
      name: ppl-app-blue
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "v1.0.4"

  - target:
      kind: Deployment
      name: ppl-app-green
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "v1.0.4"

  - target:
      kind: Service
      name: ppl-app
    patch: |-
      - op: replace
        path: /spec/selector/color
        value: blue