apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ppl-app

resources:
  - ../../base

images:
  - name: PLACEHOLDER_IMAGE
    newName: docker.io/stevensetiawankuliah/ppl-c-steven-app
    newTag: sha-b42248e