apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ppl-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/setiawans/ppl-software-deployment.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: ppl-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: Service
      name: ppl-app
      namespace: ppl-app
      jsonPointers:
        - /spec/selector/color
