apiVersion: apps/v1
kind: Deployment
metadata:
  name: ppl-app-blue
  labels:
    app: ppl-app
    color: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ppl-app
      color: blue
  template:
    metadata:
      labels:
        app: ppl-app
        color: blue
    spec:
      containers:
        - name: app
          image: docker.io/stevensetiawankuliah/ppl-c-steven-app:v1.0.4
          ports:
            - containerPort: 8000
          env:
            - name: APP_VERSION
              value: "v1.0.4"
            - name: APP_COLOR
              value: "blue"
            - name: APP_ENV
              value: "prod"